### ISSUE TITLE
Working Example / How-to / Tutorial

### ISSUE THREAD

**Issue by nelsonic** [ex-aws/ex_aws_lambda#12]
This is not a bug or feature request.
It's just a "thank you" 🙏 
and a link to how we got this working: https://github.com/dwyl/elixir-invoke-lambda-example
in case anyone else is stuck. 

Feel free to close if you feel it's not relevant. 
Thanks again! ❤️

**Comment by bernardd** [comment]
No problem, thanks @nelsonic! I'll close it, since it's not an open issue per se, but it'll still be here for people to find :)
